baseURL = 'https://vcscsvcscs.github.io/portfolio/'
title = 'Csongor Csaba Vargha - Cloud Developer'

# Use Hugo modules to add theme
[module]
    [[module.imports]]
        path = "github.com/hugo-toha/toha/v4"

# Basic theme configuration
[params]
  # Basic settings
  showFlags = false
  
  # GitHub link
  gitRepo = "https://github.com/vcscsvcscs/portfolio"
  gitBranch = "master"

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true